#server:
#  port: 9000
#
#spring:
#  application:
#    name: xdclass-video-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 172.16.20.102:8848
#    sentinel:
#      transport:
#        dashboard: 172.16.20.102:8858
#        port: 8720
#        clientIp: 172.16.21.198
#      eager: true
#
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.78.93.174:3306/appTest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456
#
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#
#video:
#  Title: alibaba010101